#!/bin/bash

git init

git submodule add git://github.com/kohana/core.git system
git submodule add git://github.com/kohana/database.git modules/database
git submodule add http://github.com/kohana/userguide.git modules/userguide
git submodule add http://github.com/kohana/image.git modules/image
git submodule add http://github.com/kohana/codebench.git modules/codebench
git submodule add http://github.com/kohana/auth.git modules/auth
git submodule add http://github.com/kohana/pagination.git modules/pagination
git submodule add http://github.com/kohana/orm.git modules/orm
# git submodule add http://github.com/shadowhand/sprig.git modules/sprig

git submodule init
git commit -m 'Added initial submodules'


mkdir -p application/classes/{controller,model}
mkdir -p application/{config,views}
mkdir -m 0777 -p application/{cache,logs}

echo '[^.]*' > application/logs/.gitignore
echo '[^.]*' > application/cache/.gitignore

curl -o index.php http://github.com/kohana/kohana/raw/master/index.php
curl -o application/bootstrap.php http://github.com/kohana/kohana/raw/master/application/bootstrap.php

git add index.php
git add application
git commit -m 'Added initial directory structure'
